openapi: "3.0.0"
info:
  version: 0.0.1
  title: Klimato API
  license:
    name: MIT
servers:
  - url: http://localhost:3010
paths:
  $ref: './paths/index.yml'
components:
  $ref: './components/index.yml'
